services:
  - type: web
    name: knowledge-assessment-backend
    runtime: docker
    dockerfilePath: Dockerfile
    rootDir: backend
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
