[PHP]
; extension_dir is managed by the system on Render
extension=mysqli
extension=openssl
extension=mbstring
extension=pdo_mysql

; Other necessary settings
display_errors = On
error_reporting = E_ALL
